name: erolls
channels:
  - spyder-ide
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - wget=1.19.1=he4ec0ba_0
  - ca-certificates=2017.11.5=0
  - certifi=2017.11.5=py35_0
  - openssl=1.0.2n=0
  - pypdf2=1.26.0=py35_1
  - selenium=3.6.0=py35_0
  - alabaster=0.7.10=py35h6fb19ab_0
  - anaconda-client=1.6.5=py35hd900ed1_0
  - anaconda=custom=py35h104c396_0
  - anaconda-navigator=1.6.9=py35h5f5ee00_0
  - anaconda-project=0.8.0=py35hb597f32_0
  - asn1crypto=0.22.0=py35h0d675fe_1
  - astroid=1.5.3=py35h1d0c565_0
  - astropy=2.0.2=py35h2d2a8a6_4
  - babel=2.5.0=py35ha5fc564_0
  - backports=1.0=py35hd471ac7_1
  - backports.shutil_get_terminal_size=1.0.0=py35h40844db_2
  - beautifulsoup4=4.6.0=py35h442a8c9_1
  - bitarray=0.8.1=py35h7540340_0
  - bkcharts=0.2=py35he4f7e30_0
  - blaze=0.11.3=py35ha2c9137_0
  - bleach=2.0.0=py35h055c768_0
  - bokeh=0.12.10=py35hfdb0b1d_0
  - boto=2.48.0=py35h2cfd601_1
  - bottleneck=1.2.1=py35he1b16f1_0
  - bzip2=1.0.6=h0376d23_1
  - cairo=1.14.10=haa5651f_5
  - cffi=1.10.0=py35h796c292_1
  - chardet=3.0.4=py35hb6e9ddf_1
  - click=6.7=py35h353a69f_0
  - cloudpickle=0.4.0=py35h10376d1_0
  - clyent=1.2.2=py35h491ffcb_1
  - colorama=0.3.9=py35h81e2b6c_0
  - coloredlogs=7.3.1=py35hcde8493_0
  - contextlib2=0.5.5=py35h6690dba_0
  - cryptography=2.0.3=py35hef72dfd_1
  - curl=7.55.1=hcb0b314_2
  - cycler=0.10.0=py35hc4d5149_0
  - cython=0.26.1=py35h636ebcb_0
  - cytoolz=0.8.2=py35ha53021f_0
  - dask=0.15.3=py35h52d6c43_0
  - dask-core=0.15.3=py35hdf4792c_0
  - datashape=0.5.4=py35h5b068ae_0
  - dbus=1.10.22=h3b5a359_0
  - decorator=4.1.2=py35h3a268aa_0
  - distributed=1.19.1=py35h399b246_0
  - docutils=0.14=py35hd11081d_0
  - entrypoints=0.2.3=py35h48174a2_2
  - et_xmlfile=1.0.1=py35hde8d43e_0
  - expat=2.2.4=hc00ebd1_1
  - fastcache=1.0.2=py35hec2bbaa_0
  - filelock=2.0.12=py35h7855d60_0
  - flask=0.12.2=py35h679e90e_0
  - flask-cors=3.0.3=py35h9b2065d_0
  - fontconfig=2.12.4=h88586e7_1
  - freetype=2.8=h52ed37b_0
  - get_terminal_size=1.0.0=haa9412d_0
  - gevent=1.2.2=py35he064abf_0
  - glib=2.53.6=hc861d11_1
  - glob2=0.5=py35h98a1f2a_1
  - gmp=6.1.2=hb3b607b_0
  - gmpy2=2.0.8=py35h89a7545_1
  - graphite2=1.3.10=hc526e54_0
  - greenlet=0.4.12=py35h2547b41_0
  - gst-plugins-base=1.12.2=he3457e5_0
  - gstreamer=1.12.2=h4f93127_0
  - h5py=2.7.0=py35h41d5d6e_1
  - harfbuzz=1.5.0=h2545bd6_0
  - hdf5=1.10.1=hb0523eb_0
  - heapdict=1.0.0=py35h51e6c10_0
  - html5lib=0.999999999=py35h0543385_0
  - humanfriendly=4.4.1=py35h457744f_0
  - icu=58.2=h211956c_0
  - idna=2.6=py35h8605a33_1
  - imageio=2.2.0=py35hd0a6de2_0
  - imagesize=0.7.1=py35hf008fae_0
  - intel-openmp=2018.0.0=h15fc484_7
  - ipykernel=4.6.1=py35h29d130c_0
  - ipython=6.1.0=py35h1b71439_1
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - ipywidgets=7.0.0=py35h8ebd919_0
  - isort=4.2.15=py35h44a00d2_0
  - itsdangerous=0.24=py35h7c46880_1
  - jbig=2.1=hdba287a_0
  - jdcal=1.3=py35hf1f7175_0
  - jedi=0.10.2=py35hc33c70f_0
  - jinja2=2.9.6=py35h90b8645_1
  - jpeg=9b=habf39ab_1
  - jsonschema=2.6.0=py35h4395190_0
  - jupyter=1.0.0=py35hd38625c_0
  - jupyter_client=5.1.0=py35h2bff583_0
  - jupyter_console=5.2.0=py35h4044a63_1
  - jupyter_core=4.3.0=py35he2f7985_0
  - jupyterlab=0.27.0=py35h29561ed_2
  - jupyterlab_launcher=0.4.0=py35ha4e430f_0
  - lazy-object-proxy=1.3.1=py35h4c720c6_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=h4deb6c0_3
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libpng=1.6.32=hda9c8bc_2
  - libsodium=1.0.13=h31c71d8_2
  - libssh2=1.8.0=h8c220ad_2
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - libtiff=4.0.8=h90200ff_9
  - libtool=2.4.6=hd50d1a6_0
  - libxcb=1.12=h84ff03f_3
  - libxml2=2.9.4=h6b072ca_5
  - libxslt=1.1.29=hcf9102b_5
  - llvmlite=0.20.0=py35_0
  - locket=0.2.0=py35h170bc82_1
  - lxml=4.1.0=py35ha401a81_0
  - lzo=2.10=h1bfc0ba_1
  - markupsafe=1.0=py35h4f4fcf6_1
  - matplotlib=2.1.0=py35h2cbf27e_0
  - mccabe=0.6.1=py35hd8c1f23_1
  - mistune=0.7.4=py35hfd0f961_0
  - mkl=2018.0.0=hb491cac_4
  - mkl-service=1.1.2=py35h0fc7090_4
  - mpc=1.0.3=hf803216_4
  - mpfr=3.1.5=h12ff648_1
  - mpmath=0.19=py35h5a16178_2
  - msgpack-python=0.4.8=py35h783f4c8_0
  - multipledispatch=0.4.9=py35h2ff591a_0
  - navigator-updater=0.1.0=py35h2ff6758_0
  - nbconvert=5.3.1=py35hc5194e3_0
  - nbformat=4.4.0=py35h12e6e07_0
  - ncurses=6.0=h06874d7_1
  - networkx=2.0=py35hc690e10_0
  - nltk=3.2.4=py35h7ba7875_0
  - nose=1.3.7=py35hdc64897_2
  - notebook=5.0.0=py35h65c930e_2
  - numba=0.35.0=np113py35_10
  - numexpr=2.6.2=py35h5f89caa_1
  - numpy=1.13.3=py35hd829ed6_0
  - numpydoc=0.7.0=py35he089a57_0
  - odo=0.5.1=py35h102315f_0
  - olefile=0.44=py35h2c86149_0
  - openpyxl=2.4.8=py35hd6c89d3_1
  - packaging=16.8=py35h2260b46_1
  - pandas=0.20.3=py35h85c2c75_2
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py35h1565a15_1
  - pango=1.40.11=h8191d47_0
  - partd=0.3.8=py35h68187f2_0
  - patchelf=0.9=hf79760b_2
  - path.py=10.3.1=py35hb82cfee_0
  - pathlib2=2.3.0=py35hd637de4_0
  - patsy=0.4.1=py35h51b66d5_0
  - pcre=8.41=hc71a17e_0
  - pep8=1.7.0=py35hee76f29_0
  - pexpect=4.2.1=py35h8b56cb4_0
  - pickleshare=0.7.4=py35hd57304d_0
  - pillow=4.2.1=py35h03abc04_0
  - pip=9.0.1=py35haa8ec2a_3
  - pixman=0.34.0=h83dc358_2
  - pkginfo=1.4.1=py35hb526c55_1
  - ply=3.10=py35h459f1a0_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - psutil=5.4.0=py35ha5baf80_0
  - ptyprocess=0.5.2=py35h38ce0a3_0
  - py=1.4.34=py35hd71111f_1
  - pycodestyle=2.3.1=py35h8d2105a_0
  - pycosat=0.6.2=py35h9693557_1
  - pycparser=2.18=py35h61b3040_1
  - pycrypto=2.6.1=py35h9852db7_1
  - pycurl=7.43.0=py35h7a9665c_3
  - pyflakes=1.6.0=py35hd1da72e_0
  - pygments=2.2.0=py35h0f41973_0
  - pylint=1.7.4=py35h319e60b_0
  - pyodbc=4.0.17=py35h89a430b_0
  - pyopenssl=17.2.0=py35h1d2a76c_0
  - pyparsing=2.2.0=py35h041ed72_1
  - pyqt=5.6.0=py35h0e41ada_5
  - pysocks=1.6.7=py35h6aefbb0_1
  - pytables=3.4.2=py35hfa98db7_2
  - pytest=3.2.1=py35hc97c719_1
  - python=3.5.4=he2c66cf_20
  - python-dateutil=2.6.1=py35h90d5b31_1
  - pytz=2017.2=py35h9225bff_1
  - pywavelets=0.5.2=py35h53ec731_0
  - pyyaml=3.12=py35h46ef4ae_1
  - pyzmq=16.0.2=py35h4be1f71_2
  - qt=5.6.2=h974d657_12
  - qtawesome=0.4.4=py35hd68ff89_0
  - qtconsole=4.3.1=py35h4626a06_0
  - qtpy=1.3.1=py35h881af26_0
  - readline=7.0=hac23ff0_3
  - requests=2.18.4=py35hb9e6ad1_1
  - rope=0.10.5=py35h31d6b7c_0
  - ruamel_yaml=0.11.14=py35h8e2c16b_2
  - scikit-image=0.13.0=py35h3573165_1
  - scikit-learn=0.19.1=py35hbf1f462_0
  - scipy=0.19.1=py35ha8f041b_3
  - seaborn=0.8.0=py35h15a2772_0
  - setuptools=36.5.0=py35ha8c1747_0
  - simplegeneric=0.8.1=py35h2ec4104_0
  - singledispatch=3.4.0.3=py35h0cd4ec3_0
  - sip=4.18.1=py35h9eaea60_2
  - six=1.11.0=py35h423b573_1
  - snowballstemmer=1.2.1=py35h5435977_0
  - sortedcollections=0.5.3=py35hb2f60ff_0
  - sortedcontainers=1.5.7=py35h683703c_0
  - sphinx=1.6.3=py35hea25a1c_0
  - sphinxcontrib=1.0=py35hcb7efd2_1
  - sphinxcontrib-websupport=1.0.1=py35h3537809_1
  - spyder=3.2.4=py35h27cea69_0
  - sqlalchemy=1.1.13=py35h4911131_0
  - sqlite=3.20.1=h6d8b0f3_1
  - statsmodels=0.8.0=py35haa9d50b_0
  - sympy=1.1.1=py35h919b29a_0
  - tblib=1.3.2=py35hf1eb0b4_0
  - terminado=0.6=py35hce234ed_0
  - testpath=0.3.1=py35had42eaf_0
  - tk=8.6.7=h5979e9b_1
  - toolz=0.8.2=py35h90f1797_0
  - tornado=4.5.2=py35hf879e1d_0
  - traitlets=4.3.2=py35ha522a97_0
  - typing=3.6.2=py35hcadae7e_0
  - unicodecsv=0.14.1=py35h4805c0c_0
  - unixodbc=2.3.4=hc36303a_1
  - urllib3=1.22=py35h2ab6e29_0
  - wcwidth=0.1.7=py35hcd08066_0
  - webencodings=0.5.1=py35hb6cf162_1
  - werkzeug=0.12.2=py35hbfc1ea6_0
  - wheel=0.29.0=py35h601ca99_1
  - widgetsnbextension=3.0.2=py35h0be620c_1
  - wrapt=1.10.11=py35hfdafd39_0
  - xlrd=1.1.0=py35h45a0a2a_1
  - xlsxwriter=1.0.2=py35h8ee9321_0
  - xlwt=1.3.0=py35h884a0cf_0
  - xz=5.2.3=h2bcbf08_1
  - yaml=0.1.7=h96e3832_1
  - zeromq=4.2.2=hb0b69da_1
  - zict=0.1.3=py35h29275ca_0
  - zlib=1.2.11=hfbfcf68_1
  - spyder-terminal=0.2.3=py35_0
  - pip:
    - easyprocess==0.2.3
    - keras==2.0.4
    - pyvirtualdisplay==0.2.1
    - tables==3.4.2
    - theano==0.9.0
prefix: /home/dhingratul/anaconda2/envs/erolls

